name: travel_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # state management
  get: 4.6.5

  # Data
  shared_preferences: 2.2.0
  get_storage: 2.1.1

  # UI
  flutter_screenutil: 5.9.0
  flutter_svg: 2.0.7
  lottie: 2.5.0
  mask_text_input_formatter: 2.5.0
  smooth_page_indicator: 1.0.1

  # IAP
  purchases_flutter: 5.3.0

  # Firebase
  firebase_core: 2.15.0
  firebase_dynamic_links: 5.3.4
  firebase_messaging: 14.6.5

  # Utils & Helpers
  android_id: 0.3.3
  collection:
  connectivity_plus: 4.0.1
  device_info_plus: 9.0.2
  flutter_email_sender: 6.0.1
  flutter_native_timezone_updated_gradle: 2.0.3
  http: 1.1.0
  image_picker: 1.0.1
  in_app_review: 2.0.6
  intl: 0.18.1
  path_provider: 2.0.15
  permission_handler: 10.4.3
  rxdart: 0.27.7
  share_plus: 7.0.2
  timezone: 0.9.2
  url_launcher: 6.1.12

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter

  # Notification
  flutter_local_notifications: 15.1.0+1
  mixpanel_flutter: ^2.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - locale/
    - assets/icons/
    - assets/images/
    - assets/json/
    - assets/sounds/

  fonts:
    - family: DMSans
      fonts:
        - asset: assets/fonts/DMSans-Bold.ttf
        - asset: assets/fonts/DMSans-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/DMSans-Italic.ttf
          style: italic
        - asset: assets/fonts/DMSans-Medium.ttf
        - asset: assets/fonts/DMSans-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/DMSans-Regular.ttf
 
